#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

IBDEV=rxe0
NETDEV=occl-rxe0
ADDR=10.99.0.1
PREFIX=24

usage() {
  cat <<'EOF'
Enable the software RoCE (rdma_rxe) device so this machine can run the RDMA and
zero-copy RDMA test suites without RDMA hardware.

  sudo scripts/setup_softroce.sh            # bring the device up (interactive)
       scripts/setup_softroce.sh --status   # show the current state, no root
  sudo scripts/setup_softroce.sh --down     # tear the device down

The wizard loads ib_uverbs / rdma_cm / rdma_ucm / rdma_rxe, creates a private
dummy netdev (occl-rxe0, 10.99.0.1/24), and attaches rxe0 to it. Both ranks on
this host then share rxe0 and talk over rxe's own loopback path, which is what
OriginCCL's first-active-device probe expects.

Re-running is safe: every stage reuses what already exists.
EOF
}

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    printf '\n  %sThis step loads kernel modules and creates links, so it needs root.%s\n' "$YELLOW" "$RESET"
    printf '  Run it as:  sudo %s\n\n' "$0"
    exit 4
  fi
}

show_status() {
  if [[ -d /sys/module/rdma_rxe ]]; then
    say "${GREEN}rdma_rxe module loaded${RESET}"
  else
    say "rdma_rxe module not loaded"
  fi
  say "netdev $NETDEV:"
  ip -br addr show "$NETDEV" 2>/dev/null | sed 's/^/    /' || say "    (absent)"
  say "rdma link:"
  rdma link show 2>/dev/null | sed 's/^/    /' || say "    (none)"
  say "devices:"
  ibv_devices 2>/dev/null | sed 's/^/    /' || true
}

teardown() {
  say "Deleting the rxe device and netdev. Kernel modules are left loaded:"
  say "rdma_cm is already in use by rpcrdma/ib_iser on this host, so rmmod would fail."
  local links=""
  links=$(rdma link show 2>/dev/null || true)
  if [[ "$links" == *"link ${IBDEV}/"* ]]; then
    rdma link delete "$IBDEV"
    say "${GREEN}deleted rdma link $IBDEV${RESET}"
  else
    note "no rdma link $IBDEV, nothing to delete"
  fi
  if ip link show "$NETDEV" >/dev/null 2>&1; then
    ip link delete "$NETDEV"
    say "${GREEN}deleted netdev $NETDEV${RESET}"
  else
    note "no netdev $NETDEV, nothing to delete"
  fi
}

case "${1:-}" in
  --down)
    require_root
    teardown
    exit 0
    ;;
  --status)
    show_status
    exit 0
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  "")
    ;;
  *)
    printf '  %sunknown option: %s%s\n\n' "$YELLOW" "$1" "$RESET"
    usage
    exit 4
    ;;
esac

require_root

banner "SoftRoCE (rdma_rxe) for OriginCCL"

# ── Stage 1: kernel modules ───────────────────────────────────────────────
stage "Load the SoftRoCE kernel modules"
say "rxe is the software RoCE transport. ib_uverbs and rdma_cm/rdma_ucm are the"
say "character devices OriginCCL opens (librdmacm opens /dev/infiniband/rdma_cm)."
step "modprobe ib_uverbs rdma_cm rdma_ucm rdma_rxe"
modprobe ib_uverbs
modprobe rdma_cm
modprobe rdma_ucm
modprobe rdma_rxe
note "loaded: $(lsmod | awk '$1 ~ /^(rdma_rxe|rdma_ucm|rdma_cm|ib_uverbs)$/ {printf "%s ", $1}')"
if [[ -c /dev/infiniband/rdma_cm && -c /dev/infiniband/uverbs0 ]]; then
  say "${GREEN}/dev/infiniband/{rdma_cm,uverbs0} present${RESET}"
else
  warn "missing device nodes; found: $(ls -1 /dev/infiniband/ 2>/dev/null | tr '\n' ' ')"
fi
pause

# ── Stage 2: the netdev rxe binds to ──────────────────────────────────────
stage "Create the netdev rxe binds to"
say "rxe needs an UP netdev with a valid MAC and an IPv4 address so it can publish"
say "a RoCEv2 GID. A private dummy link keeps your real network untouched."
step "ip link add $NETDEV type dummy && ip addr replace $ADDR/$PREFIX dev $NETDEV && ip link set $NETDEV up"
if ip link show "$NETDEV" >/dev/null 2>&1; then
  note "$NETDEV already exists, reusing it"
else
  ip link add "$NETDEV" type dummy
fi
ip addr replace "$ADDR/$PREFIX" dev "$NETDEV"
ip link set "$NETDEV" up
ip -br addr show "$NETDEV"
pause

# ── Stage 3: attach rxe0 ──────────────────────────────────────────────────
stage "Attach $IBDEV to that netdev"
say "Exactly one rxe device is wanted, and this is the important part:"
say "OriginCCL's Probe() returns the first device with an active port, so both"
say "ranks on this host attach to $IBDEV and reach each other through rxe's own"
say "loopback path (rxe_loopback / RXE_LOOPBACK_MASK). Two rxe devices on one"
say "host would NOT work: a packet for a local address is delivered with"
say "skb->dev = lo, and rxe_udp_encap_recv() drops anything not bound to an rxe."
step "rdma link add $IBDEV type rxe netdev $NETDEV"
links=$(rdma link show 2>/dev/null || true)
if [[ "$links" == *"link ${IBDEV}/"* ]]; then
  note "$IBDEV already attached, reusing it"
else
  rdma link add "$IBDEV" type rxe netdev "$NETDEV"
fi
rdma link show
ibv_devices
devinfo=$(ibv_devinfo -v -d "$IBDEV" 2>/dev/null || true)
if [[ "$devinfo" == *"::ffff:${ADDR}"* ]]; then
  say "${GREEN}RoCEv2 GID ::ffff:${ADDR} is published${RESET}"
else
  warn "no ::ffff:${ADDR} GID; GID table is:"
  printf '%s\n' "$devinfo" | sed -n 's/^/    /p' | sed -n '/GID\[/p'
fi
pause

# ── Stage 4: prove loopback RDMA works ────────────────────────────────────
stage "Prove same-host RDMA loopback works"
say "ibv_rc_pingpong server + client on $IBDEV walks the same librdmacm path OriginCCL"
say "uses (rdma_bind_addr / rdma_resolve_addr / RC queue pair), so this is the"
say "pre-flight check for the test suite."
srv_log=$(mktemp /tmp/softroce-pingpong-srv.XXXXXX)
cli_log=$(mktemp /tmp/softroce-pingpong-cli.XXXXXX)
ibv_rc_pingpong -d "$IBDEV" -g 0 >"$srv_log" 2>&1 &
srv_pid=$!
sleep 2
if timeout 20 ibv_rc_pingpong -d "$IBDEV" -g 0 "$ADDR" >"$cli_log" 2>&1; then
  say "${GREEN}loopback RDMA works${RESET}"
  tail -n 3 "$cli_log" | sed 's/^/    /'
else
  warn "loopback RDMA failed; the client said:"
  tail -n 8 "$cli_log" | sed 's/^/    /'
  warn "the server said:"
  tail -n 5 "$srv_log" | sed 's/^/    /'
  warn "if this is about the GID, retry with another -g index from: ibv_devinfo -v -d $IBDEV"
  SKIPPED+=("loopback RDMA verification")
fi
kill "$srv_pid" 2>/dev/null || true
wait "$srv_pid" 2>/dev/null || true
rm -f "$srv_log" "$cli_log"
note "teardown when you are done:  sudo $0 --down"
pause

finish
